version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./proxy.conf:/etc/nginx/extra-conf.d/proxy.conf
    ports:
      - 8080:8080
    depends_on:
      - auth
      - catalog

  nats-srv:
    container_name: nats-srv
    image: nats-streaming:0.17.0
    restart: unless-stopped
    command: -p 4222 -m 8222 -hbi 5s -hbt 5s -hbf 2 -SD -cid ticketing
    ports:
      - 4222
      - 8222:8222

  auth-mongo-srv:
    container_name: auth-mongo-srv
    image: mongo
    restart: unless-stopped
    ports:
      - 27017

  auth:
    container_name: auth
    restart: unless-stopped
    image: phill-catalog-auth
    build:
      context: auth
    # volumes:
    #   - ./auth:/app
    ports:
      - 3000
    environment:
      JWT_KEY: ticketing
      MONGO_URI: mongodb://auth-mongo-srv:27017/auth
      NODE_ENV: test
    depends_on:
      - auth-mongo-srv

  catalog-mongo-srv:
    container_name: catalog-mongo-srv
    image: mongo
    restart: unless-stopped
    ports:
      - 27017

  catalog:
    container_name: catalog
    restart: unless-stopped
    image: catalog
    build:
      context: catalog
    # volumes:
    #   - ./catalog:/app
    ports:
      - 3000
    environment:
      JWT_KEY: ticketing
      MONGO_URI: mongodb://auth-mongo-srv:27017/catalog
      NATS_CLIENT_ID: catalog
      NATS_URL: http://nats-srv:4222
      NATS_CLUSTER_ID: ticketing
    depends_on:
      - catalog-mongo-srv
      - nats-srv

  worker-redis:
    container_name: worker-redis
    image: redis
    restart: unless-stopped
    ports:
      - 6379

  worker:
    container_name: worker
    restart: unless-stopped
    image: worker
    build:
      context: worker
    # volumes:
    #   - ./worker:/app
    ports:
      - 3000
    environment:
      NATS_CLIENT_ID: worker
      NATS_URL: http://nats-srv:4222
      NATS_CLUSTER_ID: ticketing
      SUPPLY_CHAIN_URL: https://ev5uwiczj6.execute-api.eu-central-1.amazonaws.com/test
      REDIS_HOST: worker-redis
    depends_on:
      - nats-srv
